"""empty message

Revision ID: 6e9109657996
Revises: 
Create Date: 2023-10-13 15:00:58.246262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e9109657996'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skap',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('number_id', sa.Integer(), nullable=True),
    sa.Column('area', sa.String(), nullable=True),
    sa.Column('turno', sa.String(), nullable=True),
    sa.Column('q1', sa.Integer(), nullable=True),
    sa.Column('q2', sa.Integer(), nullable=True),
    sa.Column('q3', sa.Integer(), nullable=True),
    sa.Column('q4', sa.Integer(), nullable=True),
    sa.Column('q5', sa.Integer(), nullable=True),
    sa.Column('q6', sa.Integer(), nullable=True),
    sa.Column('q7', sa.Integer(), nullable=True),
    sa.Column('q8', sa.Integer(), nullable=True),
    sa.Column('q9', sa.Integer(), nullable=True),
    sa.Column('q10', sa.Integer(), nullable=True),
    sa.Column('q11', sa.Integer(), nullable=True),
    sa.Column('q12', sa.Integer(), nullable=True),
    sa.Column('q13', sa.Integer(), nullable=True),
    sa.Column('q14', sa.Integer(), nullable=True),
    sa.Column('q15', sa.Integer(), nullable=True),
    sa.Column('q16', sa.Integer(), nullable=True),
    sa.Column('q17', sa.Integer(), nullable=True),
    sa.Column('q18', sa.Integer(), nullable=True),
    sa.Column('q19', sa.Integer(), nullable=True),
    sa.Column('q20', sa.Integer(), nullable=True),
    sa.Column('q21', sa.Integer(), nullable=True),
    sa.Column('q22', sa.Integer(), nullable=True),
    sa.Column('q23', sa.Integer(), nullable=True),
    sa.Column('q24', sa.Integer(), nullable=True),
    sa.Column('q25', sa.Integer(), nullable=True),
    sa.Column('q26', sa.Integer(), nullable=True),
    sa.Column('q27', sa.Integer(), nullable=True),
    sa.Column('q28', sa.Integer(), nullable=True),
    sa.Column('q29', sa.Integer(), nullable=True),
    sa.Column('q30', sa.Integer(), nullable=True),
    sa.Column('q31', sa.Integer(), nullable=True),
    sa.Column('q32', sa.Integer(), nullable=True),
    sa.Column('q33', sa.Integer(), nullable=True),
    sa.Column('q34', sa.Integer(), nullable=True),
    sa.Column('q35', sa.Integer(), nullable=True),
    sa.Column('q36', sa.Integer(), nullable=True),
    sa.Column('q37', sa.Integer(), nullable=True),
    sa.Column('q38', sa.Integer(), nullable=True),
    sa.Column('q39', sa.Integer(), nullable=True),
    sa.Column('q40', sa.Integer(), nullable=True),
    sa.Column('q41', sa.Integer(), nullable=True),
    sa.Column('q42', sa.Integer(), nullable=True),
    sa.Column('q43', sa.Integer(), nullable=True),
    sa.Column('q44', sa.Integer(), nullable=True),
    sa.Column('q45', sa.Integer(), nullable=True),
    sa.Column('q46', sa.Integer(), nullable=True),
    sa.Column('q47', sa.Integer(), nullable=True),
    sa.Column('q48', sa.Integer(), nullable=True),
    sa.Column('q49', sa.Integer(), nullable=True),
    sa.Column('q50', sa.Integer(), nullable=True),
    sa.Column('q51', sa.Integer(), nullable=True),
    sa.Column('q52', sa.Integer(), nullable=True),
    sa.Column('q53', sa.Integer(), nullable=True),
    sa.Column('q54', sa.Integer(), nullable=True),
    sa.Column('q55', sa.Integer(), nullable=True),
    sa.Column('q56', sa.Integer(), nullable=True),
    sa.Column('q57', sa.Integer(), nullable=True),
    sa.Column('q58', sa.Integer(), nullable=True),
    sa.Column('q59', sa.Integer(), nullable=True),
    sa.Column('q60', sa.Integer(), nullable=True),
    sa.Column('q61', sa.Integer(), nullable=True),
    sa.Column('q62', sa.Integer(), nullable=True),
    sa.Column('q63', sa.Integer(), nullable=True),
    sa.Column('q64', sa.Integer(), nullable=True),
    sa.Column('q65', sa.Integer(), nullable=True),
    sa.Column('q66', sa.Integer(), nullable=True),
    sa.Column('q67', sa.Integer(), nullable=True),
    sa.Column('q68', sa.Integer(), nullable=True),
    sa.Column('q69', sa.Integer(), nullable=True),
    sa.Column('q70', sa.Integer(), nullable=True),
    sa.Column('q71', sa.Integer(), nullable=True),
    sa.Column('q72', sa.Integer(), nullable=True),
    sa.Column('q73', sa.Integer(), nullable=True),
    sa.Column('q74', sa.Integer(), nullable=True),
    sa.Column('q75', sa.Integer(), nullable=True),
    sa.Column('q76', sa.Integer(), nullable=True),
    sa.Column('q77', sa.Integer(), nullable=True),
    sa.Column('q78', sa.Integer(), nullable=True),
    sa.Column('q79', sa.Integer(), nullable=True),
    sa.Column('q80', sa.Integer(), nullable=True),
    sa.Column('q81', sa.Integer(), nullable=True),
    sa.Column('q82', sa.Integer(), nullable=True),
    sa.Column('q83', sa.Integer(), nullable=True),
    sa.Column('q84', sa.Integer(), nullable=True),
    sa.Column('q85', sa.Integer(), nullable=True),
    sa.Column('q86', sa.Integer(), nullable=True),
    sa.Column('q87', sa.Integer(), nullable=True),
    sa.Column('q88', sa.Integer(), nullable=True),
    sa.Column('q89', sa.Integer(), nullable=True),
    sa.Column('q90', sa.Integer(), nullable=True),
    sa.Column('q91', sa.Integer(), nullable=True),
    sa.Column('q92', sa.Integer(), nullable=True),
    sa.Column('q93', sa.Integer(), nullable=True),
    sa.Column('q94', sa.Integer(), nullable=True),
    sa.Column('q95', sa.Integer(), nullable=True),
    sa.Column('q96', sa.Integer(), nullable=True),
    sa.Column('q97', sa.Integer(), nullable=True),
    sa.Column('q98', sa.Integer(), nullable=True),
    sa.Column('q99', sa.Integer(), nullable=True),
    sa.Column('q100', sa.Integer(), nullable=True),
    sa.Column('q101', sa.Integer(), nullable=True),
    sa.Column('q102', sa.Integer(), nullable=True),
    sa.Column('q103', sa.Integer(), nullable=True),
    sa.Column('q104', sa.Integer(), nullable=True),
    sa.Column('q105', sa.Integer(), nullable=True),
    sa.Column('q106', sa.Integer(), nullable=True),
    sa.Column('q107', sa.Integer(), nullable=True),
    sa.Column('q108', sa.Integer(), nullable=True),
    sa.Column('q109', sa.Integer(), nullable=True),
    sa.Column('q110', sa.Integer(), nullable=True),
    sa.Column('resultado', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('cargo', sa.String(), nullable=True),
    sa.Column('area', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('skap')
    # ### end Alembic commands ###
